name: to_do_list
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  date_picker_timeline: ^1.2.5
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  intl: ^0.18.1
  sqflite: ^2.3.0
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/task.svg
    - assets/images/task.jpg
